config/routes.rb
RedmineApp::Application.routes.draw do
  match 'vacation/audit', :to => 'vacation#audit', :via => [:get, :post]
  match 'vacation/aduit/:id', :to => 'vacation#audit', :via => [:get, :post]
  match 'vacation/auditpass', :to => 'vacation#auditpass', :via => [:get, :post]
  match 'vacation/aduitpass/:id', :to => 'vacation#auditpass', :via => [:get, :post]
  match 'vacation/auditpasstime', :to => 'vacation#auditpasstime', :via => [:get, :post]
  match 'vacation/aduitpasstime/:id', :to => 'vacation#auditpasstime', :via => [:get, :post]
  resources :vacation
end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
  unloadable
end

app/controllers/vacation_controller.rb
class VacationController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index,:audit]
  before_action :set_vacation, only: [:show, :edit, :update, :destroy,:auditpass]
  include CustomFieldsHelper
  def new
    @vacation = Vacation.new();
    @users = User.all

  end

  def index
    curt_uid = User.current.id
    @vacations = Vacation.where(applyId: curt_uid)
  end

  def audit
    curt_uid = User.current.id
    @vacations = Vacation.where(auditId: curt_uid, statusShow: '待审批')
    @time_logs = TimeEntry.where(audit_id: curt_uid, audit_status: '待审核')
  end
  def auditpass
    @vacation.update_attribute(:statusShow,'审批通过')
    curt_uid = User.current.id
    @vacations = Vacation.where(auditId: curt_uid, statusShow: '待审批')
    @time_logs = TimeEntry.where(audit_id: curt_uid, audit_status: '待审核')
    render :audit
  end

  def auditpasstime
    curt_uid = User.current.id
    @timelog = TimeEntry.find_by(id: params[:id])
    @timelog.update_attribute(:audit_status,'审批通过')
    @vacations = Vacation.where(auditId: curt_uid, statusShow: '待审批')
    @time_logs = TimeEntry.where(audit_id: curt_uid, audit_status: '待审核')
    render :audit
  end

  def create 
    @vacation = Vacation.new(vacation_params)
    @vacation.applyId = User.current.id
    @vacation.applyName = User.current.name
    @vacation.statusShow = '待审批'
    @vacation.auditName = User.find_by(id: @vacation.auditId).name
    respond_to do |format|
      if @vacation.save
        format.html { redirect_to @vacation, notice: '休假申请已提交.' }
        format.json { render :show, status: :created, location: @vacation }
      else
        format.html { render :new }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def edit
    @users = User.all
  end
 
  def destroy
    @vacation.destroy
    @vacations = Vacation.all
    respond_to do |format|
      format.html { redirect_to action: :index, notice: '休假申请已删除.' }
      format.js
    end
  end

  def show
    @users = User.all
  end

  def update
    @vacation.auditName = User.find_by(id: @vacation.auditId).name
    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to @vacation, notice: '休假申请已更新.' }
        format.json { render :show, status: :updated, location: @vacation }
      else
        format.html { render :edit }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  

  private
    def set_vacation
      @vacation = Vacation.find_by(id: params[:id])
    end

    def vacation_params
      params.require(:vacation).permit!
    end
end

app/helpers/vacation_helper.rb
module VacationHelper
    
end

app/views/vacation/audit.html.erb
<h1>审批中心</h1> 
<div class="autoscroll">
<h2>休假审批</h2>
<table class="list odd-even">
  <tr class="group open">
    <th class="checkbox hide-when-print">申请人</th>
    <th class="checkbox hide-when-print">开始日期</th>
    <th class="checkbox hide-when-print">结束日期</th>
    <th class="checkbox hide-when-print">请假时长</th>
    <th class="checkbox hide-when-print">审批人</th>
    <th class="checkbox hide-when-print">审批进度</th>

    <th class="checkbox hide-when-print"></th>
    <th class="checkbox hide-when-print"></th>
    <th class="checkbox hide-when-print"></th>
    <th class="checkbox hide-when-print"></th>
  </tr>
 
<% @vacations.each do |vacation| %>
  <tr class="time-entry <%= cycle("odd", "even") %> hascontextmenu" >
    <td><%= vacation.applyName %></td>
    <td><%= vacation.start %></td>
    <td><%= vacation.end %></td>
    <td><%= vacation.hours %></td>
    <td><%= vacation.auditName %></td>
    <td><%= vacation.statusShow %></td>
    <td><%= link_to "查看", vacation %></td>
    <td><%= link_to "修改", edit_vacation_path(vacation) %></td>
    <td><%= link_to "审批通过", ({:controller =>'vacation',:action => 'auditpass',:id => vacation.id}), data: { confirm: "确定审批通过?" } %></td>
    <td><%= link_to "删除", vacation, method: :delete, data: { confirm: "确定删除?" } %></td>
  </tr>
<% end %>
</table>
</div>
 
<div>
<h2>工时审批</h2>
<table class="list odd-even">
  <tr class="group open">
    <th class="checkbox hide-when-print">用户</th>
    <th class="checkbox hide-when-print">日期</th>
    <th class="checkbox hide-when-print">时长</th>
    <th class="checkbox hide-when-print">说明</th>
    <th class="checkbox hide-when-print"></th>
    <th class="checkbox hide-when-print"></th>
    <th class="checkbox hide-when-print"></th>
    <th class="checkbox hide-when-print"></th>

  </tr>
 
<% @time_logs.each do |time_log| %>
  <tr class="time-entry <%= cycle("odd", "even") %> hascontextmenu">
    <td><%= time_log.username %></td>
    <td><%= time_log.spent_on %></td>
    <td><%= time_log.hours %></td>
    <td><%= time_log.comments %></td>
    <td><%= link_to "修改", edit_time_entry_path(time_log) %></td>
    <td><%= link_to "审批通过", ({:controller =>'vacation',:action => 'auditpasstime',:id => time_log.id}), data: { confirm: "确定审批通过?" } %></td>
  </tr>
<% end %>
</table>
</div>

<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'vacation', :plugin => 'ingeekvacation' %>
    <%= javascript_include_tag "vacation" , :plugin => 'ingeekvacation' %>
<% end %>

app/views/vacation/edit.html.erb
<%= form_for @vacation, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
<div class="box tabular">
 <p>
  <label  class="required" for="start" id="start"><%="休假开始时间:"%></label>
  <%= f.date_field :start, :size => 10 , :required => true %>
  </p>
  <p>
  <label  class="required" for="end" id="end"><%="休假结束时间:"%></label>
  <%= f.date_field :end, :size => 10 , :required => true %>
  </p>
  <p>
  <label  class="required" for="hours" id="hours"><%="请假时长:"%></label>
  <%= f.text_field :hours, size: "8" , :required => true  %> <label class="inline">小时</label>
  </p>

   <p>
   <label  class="required" for="auditId" id="auditId">审批人</label>
     <%= f.select(:auditId, options_from_collection_for_select(@users, "id", "name" ,@vacation.auditId)) %>
  </p>

  <p>
   <label  class="required" for="vatype" id="vatype">假期类型</label>
     <%= f.select(:vatype, options_for_select([["调休假", "1"], ["年假", "2"], ["病假", "3"]],@vacation.vatype)) %>
  </p>
  <p>
  <label  class="required" for="reason" id="reason"><%="休假事由:"%></label>
  <%= f.text_area :reason, size: "20x5" , :required => true  %>
  </p>
  <p><%= f.submit "确认修改" %></p>
  </div>
<% end %>

<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'vacation', :plugin => 'ingeekvacation' %>
    <%= javascript_include_tag "vacation" , :plugin => 'ingeekvacation' %>
<% end %>

app/views/vacation/index.html.erb
<h1>休假申请</h1>

<div class="contextual">
<%= link_to "新增休假申请", new_vacation_path , :class => 'icon icon-add new-vacation'  %>
</div>
 
<div>
<table class="list odd-even">
  <tr class="group open">
    <th class="checkbox hide-when-print">申请人</th>
    <th class="checkbox hide-when-print">开始日期</th>
    <th class="checkbox hide-when-print">结束日期</th>
    <th class="checkbox hide-when-print">请假时长</th>
    <th class="checkbox hide-when-print">审批人</th>
    <th class="checkbox hide-when-print">审批进度</th>
    <th class="checkbox hide-when-print"></th>
    <th class="checkbox hide-when-print"></th>
    <th class="checkbox hide-when-print"></th>
  </tr>
 
<% @vacations.each do |vacation| %>
  <tr class="time-entry <%= cycle("odd", "even") %> hascontextmenu">
    <td><%= vacation.applyName %></td>
    <td><%= vacation.start %></td>
    <td><%= vacation.end %></td>
    <td><%= vacation.hours %></td>
    <td><%= vacation.auditName %></td>
    <td><%= vacation.statusShow %></td>
    <td><%= link_to "查看", vacation %></td>
    <td><%= link_to "修改", edit_vacation_path(vacation) %></td>
    <td><%= link_to "删除", vacation, method: :delete, data: { confirm: "确定删除?" } %></td>
  </tr>
<% end %>
</table>
</div>
 

<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'vacation', :plugin => 'ingeekvacation' %>
    <%= javascript_include_tag "vacation" , :plugin => 'ingeekvacation' %>
<% end %>

app/views/vacation/new.html.erb
<%= form_for @vacation, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
<div class="box tabular">
 <p>
  <label  class="required" for="start" id="start"><%="休假开始时间:"%></label>
  <%= f.date_field :start, :size => 10 , :required => true %>
  </p>
  <p>
  <label  class="required" for="end" id="end"><%="休假结束时间:"%></label>
  <%= f.date_field :end, :size => 10 , :required => true %>
  </p>
  <p>
  <label  class="required" for="hours" id="hours"><%="请假时长:"%></label>
  <%= f.text_field :hours, size: "8" , :required => true  %> <label class="inline">小时</label>
  </p>

  <p>
   <label  class="required" for="auditId" id="auditId">审批人</label>
     <%= f.select(:auditId, options_from_collection_for_select(@users, "id", "name")) %>
  </p>

  <p>
   <label  class="required" for="vatype" id="vatype">假期类型</label>
     <%= f.select(:vatype, options_for_select([["调休假", "1"], ["年假", "2"], ["病假", "2"]])) %>
  </p>
  <p>
  <label  class="required" for="reason" id="reason"><%="休假事由:"%></label>
  <%= f.text_area :reason, size: "60x12" , :required => true  %>
  </p>
  <p><%= f.submit "请假" %></p>
  </div>
<% end %>

<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'vacation', :plugin => 'ingeekvacation' %>
<% end %>

app/views/vacation/show.html.erb
<%= form_for @vacation, url: {action: "index"}, html: {class: "nifty_form"} do |f| %>
<div class="box tabular">
 <p>
  <label  class="required" for="start" id="start"><%="休假开始时间:"%></label>
  <%= f.date_field :start, :size => 10 , :required => true  ,:disabled => true %>
  </p>
  <p>
  <label  class="required" for="end" id="end"><%="休假结束时间:"%></label>
  <%= f.date_field :end, :size => 10 , :required => true ,:disabled => true %>
  </p>
  <p>
  <label  class="required" for="hours" id="hours"><%="请假时长:"%></label>
  <%= f.text_field :hours, size: "8" , :required => true  ,:disabled => true %> <label class="inline">小时</label>
  </p>
  <p>
  <label  class="required" for="auditName" id="auditName"><%="审批人:"%></label>
  <%= f.text_field :auditName, size: "8" , :required => true  ,:disabled => true %> 
  </p>
  
  <p>
   <label  class="required" for="vatype" id="vatype">假期类型</label>
     <%= f.select(:vatype, options_for_select([["调休假", "1"], ["年假", "2"], ["病假", "3"]],@vacation.vatype),{:disabled => true} ) %>
  </p>
  
  <label  class="required" for="reason" id="reason"><%="休假事由:"%></label>
  <%= f.text_area :reason, size: "30x12" , :required => true  ,:disabled => true %>
  </p>
  <%= link_to "返回", vacation_index_path ,:class => 'icon icon-reload' %>
  </div>
<% end %>


<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'vacation', :plugin => 'ingeekvacation' %>
<% end %>